# Generated by Django 3.2 on 2025-06-28 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20250628_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtransaksi',
            name='kasir',
        ),
        migrations.AddField(
            model_name='itemtransaksi',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='kasir',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
